Avoid conflict with stdbool.h
I recently ran into an error when both `stdbool.h` and `tonc.h` were included in the same source file.
```
/opt/devkitpro/libtonc/include/tonc_types.h:189:16: error: expected identifier before numeric constant
  189 | typedef enum { false, true } bool;
      |                ^~~~~
```

This commit fixes it by checking for a standard define. :)